language: node_js

node_js:
- "8"

env:
- CODE_VERSION=1.18.0

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - g++-4.9
      - libsecret-1-dev
      - dotnet-sdk-2.0.2

install:
- npm ci
- npm i -g gulp
- gulp 'vsix:release:package'

script:
  - gulp 'vsix:release:unpackage'
  - gulp cov:instrument --codeExtensionPath ./vsix/extension
  - gulp test --codeExtensionPath ./vsix/extension
  - gulp cov:report --codeExtensionPath ./vsix/extension
  - npm run test:artifacts
  - 'if [[ "$TRAVIS_BRANCH" != "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run test:release; fi'

after_failure:
  - ./.travis/printLogs.sh

after_success:
  - ./.travis/printLogs.sh

deploy:
  provider: releases
  api_key:
    secure: IccNv4d/b3/c2Wg/A39L/gfNPT0nBMpcf2b5PlEy+U79ii9hKHq681hHCJ/NPhwUjWOfSfgFXRoTJVYIHuMnT7WLnSqfqiiPUo82z0ulZQOEEdt8oVHoABm5SzAPQqe6Lo/SC+2zYV6TgqP/i9qVN0TuyA1jH00hmpBjnozO98GyuJIeUYwvEBkhJttcO0HLb836td5OxG8SDRo9kFauITNZAFQA8yVlsFmCJF1Di7Oncmcjcd5aHm9PnbgQytHg+iWMhBZuHXfB9hV4J0tsMZB+XPxvkS74dASuKjEIIdB66GXoVL5BzJmopY3gQVYpK5wK+HH4PwwpdZ1BY0qW4zmUCwwlNXSIVX8IjCiRt/5Bc3hqpY8zahIFKW37ZbHSVH1kKK9+fmEt5iy4HSqGGxmSXVrQGY1VJhsol/0Yu326L9J35AKhQeYKQvIdUQy4LiIN8NTUtEZr5Nvv6+TCI0RShQgkGQrlVyknIpoq9HM915NDTRLwm3s78LptkOP6wmRk26HLOBdYG/0k15Wos7mtR6cXc+NqKZm8tPfPEn2cIzGrmQgKXuCoXu+hGoOl/2HSzDnUUxhiSVbjoCei7HRXPT+0yhDc8e+Kt1fHKDJpyj7ybICVGmexxQY41mPtAVKrX/pDBCi53QVT1a+QEAd5Y27X4S8Ko+Vqukkoq7E=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: OmniSharp/omnisharp-vscode
    tags: true
  overwrite: true

after_deploy: "find . -type f -name '*.vsix'"