blank_issues_enabled: true
contact_links:
  - name: Issue with Razor (Blazor) tooling
    url:  https://github.com/dotnet/razor/issues/new/choose
    about: Please open issues relating to the Razor tooling in dotnet/razor.