name: Branch snap
on:
  workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  check-script:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: '.config/snap-flow.json'
      configuration_file_branch: 'custom-branch-if-needed'