name: Branch snap
on:
  workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  check-script:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: '.config/snap-flow.json'

  create-pull-request:
    if: github.ref == 'refs/heads/dev/dibarbet/action_inc_version'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies 
        run: |
          npm ci
          npm i -g gulp
      - name: Update version.json
        run: gulp incrementVersionJson
      - name: Create version.json update PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update main version
          title: 'Update main version'
          branch: merge/update-main-version
