name: OmniSharp-VSCode Release CI

on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: |
          npm ci
          npm i -g gulp

    - name: Build extension package
      run: gulp 'vsix:release:package:platform-specific'

    - name: Run release tests
      run: npm run test:release

    - name: Get package version
      run: node -e "console.log('VERSION=' + require('./package.json').version)" >> $GITHUB_ENV

    - name: Upload release build (darwin-arm64)
      id: upload-release-asset-darwin-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-darwin-arm64.vsix
        asset_name: csharp-${{ env.VERSION }}-darwin-arm64.vsix
        asset_content_type: application/zip

    - name: Upload release build (darwin-x64)
      id: upload-release-asset-darwin-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-darwin-x64.vsix
        asset_name: csharp-${{ env.VERSION }}-darwin-x64.vsix
        asset_content_type: application/zip

    - name: Upload release build (linux-x64)
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-linux-x64.vsix
        asset_name: csharp-${{ env.VERSION }}-linux-x64.vsix
        asset_content_type: application/zip

    - name: Upload release build (win32-arm64)
      id: upload-release-asset-win32-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-win32-arm64.vsix
        asset_name: csharp-${{ env.VERSION }}-win32-arm64.vsix
        asset_content_type: application/zip

    - name: Upload release build (win32-ia32)
      id: upload-release-asset-win32-ia32
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-win32-ia32.vsix
        asset_name: csharp-${{ env.VERSION }}-win32-ia32.vsix
        asset_content_type: application/zip

    - name: Upload release build (win32-x64)
      id: upload-release-asset-win32-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./csharp-${{ env.VERSION }}-win32-x64.vsix
        asset_name: csharp-${{ env.VERSION }}-win32-x64.vsix
        asset_content_type: application/zip
