trigger: none
pr: none

variables:
# Variable group contains PAT for bot account.
- group: dotnet-vscode-insertion-variables

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: CI
    project: DevDiv
    source: VisualStudio.Conversations
    branch: main
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
    - stage: Upload
      jobs:
      - job: UploadToServer
        displayName: Upload to server
        pool:
          name: AzurePipelines-EO
          image: 1ESPT-Windows2022
          os: windows
        templateContext:
          isProduction: true
          inputs:
          - input: pipelineArtifact
            pipeline: CI
            artifactName: partnerDeployables-Windows
            destinationPath: $(Pipeline.Workspace)/artifacts

        steps:
        - checkout: self
          clean: true
          submodules: true
          fetchTags: false
          fetchDepth: 0

        - task: CopyFiles@2
          displayName: 'Copy files from Zip folder to staging directory'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/'
            Contents: '**/*Roslyn.LanguageServer*.zip'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/staging'
            CleanTargetFolder: true

        - task: AzureFileCopy@6
          displayName: "Copy the zip to Azure Storage"
          inputs:
            SourcePath: '$(Build.ArtifactStagingDirectory)/staging/*'
            azureSubscription: "$(AzSubscription)"
            Destination: "AzureBlob"
            storage: "$(AzStorage)"
            ContainerName: "$(AzContainerName)"

        - pwsh: |
            npm install
          displayName: 'Install tools'

        - pwsh: npm run publishRoslynCopilot -- --userName dotnet-maestro-bot --email dotnet-maestro-bot@microsoft.com --stagingDirectory '$(Build.ArtifactStagingDirectory)/staging'
          displayName: 'Create component update PR'
          env:
            GitHubPAT: $(BotAccount-dotnet-maestro-bot-PAT)
